# coding=utf-8
__author__ = 'dimv36'


ROLE_ADMIN = u'Администратор'
ROLE_HEAD_OF_ORGANIZATION = u'Руководитель организации'
ROLE_HEAD_OF_INFORMATION_SECURITY = u'Начальник службы ИБ'
ROLE_HEAD_OF_STRATEGIC_LEVEL = u'Начальник стратегического уровня'
ROLE_HEAD_OF_TACTICAL_LEVEL = u'Управляющий тактического уровня'
ROLE_HEAD_OF_OPERATIONAL_LEVEL = u'Управляющий операционного уровня'
ROLE_HEAD_OF_BASE_LEVEL = u'Управляющий базового уровня'

ROLES = [(ROLE_HEAD_OF_ORGANIZATION, ROLE_HEAD_OF_ORGANIZATION),
    (ROLE_HEAD_OF_INFORMATION_SECURITY, ROLE_HEAD_OF_INFORMATION_SECURITY),
    (ROLE_HEAD_OF_STRATEGIC_LEVEL, ROLE_HEAD_OF_STRATEGIC_LEVEL),
    (ROLE_HEAD_OF_TACTICAL_LEVEL, ROLE_HEAD_OF_TACTICAL_LEVEL),
    (ROLE_HEAD_OF_OPERATIONAL_LEVEL, ROLE_HEAD_OF_OPERATIONAL_LEVEL),
    (ROLE_HEAD_OF_BASE_LEVEL, ROLE_HEAD_OF_BASE_LEVEL)
]