DROP TABLE application_data CASCADE;
DROP TABLE investment_levels CASCADE;
DROP TABLE processes CASCADE;
DROP TABLE questions CASCADE;
DROP TABLE roles CASCADE;
DROP TABLE user_choices CASCADE;
DROP TABLE users CASCADE;