INSERT INTO investment_levels VALUES(DEFAULT, 'ISM3 LEVEL 1') RETURNING id;
INSERT INTO investment_levels VALUES(DEFAULT, 'ISM3 LEVEL 2') RETURNING id;
INSERT INTO investment_levels VALUES(DEFAULT, 'ISM3 LEVEL 3') RETURNING id;
INSERT INTO investment_levels VALUES(DEFAULT, 'ISM3 LEVEL 4') RETURNING id;
INSERT INTO investment_levels VALUES(DEFAULT, 'ISM3 LEVEL 5') RETURNING id;