INSERT INTO processes VALUES(1, 'GP-1: Управление знаниями', 4);
INSERT INTO processes VALUES(2, 'GP-2: Внутренний аудит', 4);
INSERT INTO processes VALUES(3, 'GP-3: Непрерывное улучшение СУИБ', 4);
INSERT INTO processes VALUES(4, 'SSP-1: Отчёт со сторонними организациями в вопросах ИБ', 3);
INSERT INTO processes VALUES(5, 'SSP-2: Координация', 3);
INSERT INTO processes VALUES(6, 'SSP-4: Определение должностных обязанностей', 3);
INSERT INTO processes VALUES(7, 'SSP-6: Финансирование службы ИБ', 3);
INSERT INTO processes VALUES(8, 'TSP-1: Доклад стратегическому уровню управления ИБ', 6);
INSERT INTO processes VALUES(9, 'TSP-2: Управление выделенными ресурсами', 6);
INSERT INTO processes VALUES(10, 'TSP-3: Определение целей безопасности', 6);
INSERT INTO processes VALUES(11, 'TSP-4: Управление уровнем обслуживания', 6);
INSERT INTO processes VALUES(12, 'TSP-6: Архитектура безопсности', 6);
INSERT INTO processes VALUES(13, 'TSP-7: Проверка биографии сотрудников', 6);
INSERT INTO processes VALUES(14, 'TSP-8: Безопасность сотрудников', 6);
INSERT INTO processes VALUES(15, 'TSP-9: Обучение сотрудников в области ИБ', 6);
INSERT INTO processes VALUES(16, 'TSP-10: Дисциплина', 6);
INSERT INTO processes VALUES(17, 'TSP-11: Осознание безопасности', 6);
INSERT INTO processes VALUES(18, 'TSP-13: Страхование', 6);
INSERT INTO processes VALUES(19, 'TSP-14: Обеспечение информирования', 6);
INSERT INTO processes VALUES(20, 'OSP-1: Доклад тактическому уровню управления ИБ', 5);
INSERT INTO processes VALUES(21, 'OSP-2: Закупка средств безопасности', 5);
INSERT INTO processes VALUES(22, 'OSP-3: Управление активами', 5);
INSERT INTO processes VALUES(23, 'OSP-4: Управление изменениями в инфраструктуре IT', 5);
INSERT INTO processes VALUES(24, 'OSP-5: Управление обновлением в IT', 5);
INSERT INTO processes VALUES(25, 'OSP-6:', 5);
INSERT INTO processes VALUES(26, 'OSP-7:', 5);
INSERT INTO processes VALUES(27, 'OSP-8:', 5);
INSERT INTO processes VALUES(28, 'OSP-9:', 5);
INSERT INTO processes VALUES(29, 'OSP-10:', 5);
INSERT INTO processes VALUES(30, 'OSP-11: Контроль доступа', 5);
INSERT INTO processes VALUES(31, 'OSP-12:', 5);
INSERT INTO processes VALUES(32, 'OSP-16: Сегментация и управление фильтрацией', 5);
INSERT INTO processes VALUES(33, 'OSP-17: Управление защитой от вредоносных программ', 5);
INSERT INTO processes VALUES(34, 'OSP-10: Управление резервными копиями', 5);
INSERT INTO processes VALUES(35, 'OSP-21: Анализ качества и соответствия информации', 5);
