INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'GP-1: Управление знаниями', 4) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'GP-2: Внутренний аудит', 4) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'GP-3: Непрерывное улучшение СУИБ', 4) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'SSP-1: Отчёт со сторонними организациями в вопросах ИБ', 3) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'SSP-2: Координация', 3) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'SSP-4: Определение должностных обязанностей', 3) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'SSP-6: Финансирование службы ИБ', 3) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'TSP-1: Доклад стратегическому уровню управления ИБ', 6) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'TSP-2: Управление выделенными ресурсами', 6) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'TSP-3: Определение целей безопасности', 6) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'TSP-4: Управление уровнем обслуживания', 6) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'TSP-6: Архитектура безопсности', 6) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'TSP-7: Проверка биографии сотрудников', 6) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'TSP-8: Безопасность сотрудников', 6) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'TSP-9: Обучение сотрудников в области ИБ', 6) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'TSP-10: Дисциплина', 6) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'TSP-11: Осознание безопасности', 6) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'TSP-13: Страхование', 6) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'TSP-14: Обеспечение информирования', 6) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-1: Доклад тактическому уровню управления ИБ', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-2: Закупка средств безопасности', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-3: Управление активами', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-4: Управление изменениями в инфраструктуре IT', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-5: Управление обновлением в IT', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-6:', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-7:', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-8:', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-9:', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-10:', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-11: Контроль доступа', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-12:', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-16: Сегментация и управление фильтрацией', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-17: Управление защитой от вредоносных программ', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-10: Управление резервными копиями', 5) RETURNING id;
INSERT INTO processes(id, name, role_id) VALUES(DEFAULT, 'OSP-21: Анализ качества и соответствия информации ', 5) RETURNING id;
