INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'GP-1: Управление знаниями', true, 4) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'GP-2: Внутренний аудит', false, 4) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'GP-3: Непрерывное улучшение СУИБ', true, 4) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'SSP-1: Отчёт со сторонними организациями в вопросах ИБ', true, 3) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'SSP-2: Координация', true, 3) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'SSP-4: Определение должностных обязанностей', false, 3) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'SSP-6: Финансирование службы ИБ', true, 3) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'TSP-1: Доклад стратегическому уровню управления ИБ', true, 6) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'TSP-2: Управление выделенными ресурсами', true, 6) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'TSP-3: Определение целей безопасности', true, 6) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'TSP-4: Управление уровнем обслуживания', true, 6) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'TSP-6: Архитектура безопсности', false, 6) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'TSP-7: Проверка биографии сотрудников', false, 6) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'TSP-8: Безопасность сотрудников', false, 6) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'TSP-9: Обучение сотрудников в области ИБ', false, 6) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'TSP-10: Дисциплина', false, 6) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'TSP-11: Осознание безопасности', false, 6) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'TSP-13: Страхование', false, 6) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'TSP-14: Обеспечение информирования', false, 6) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-1: Доклад тактическому уровню управления ИБ', true, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-2: Закупка средств безопасности', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-3: Управление ресурсами', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-4: Управление изменениями в IT', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-5: Управление обновлением в IT', true, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-6: Управление очисткой в IT', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-7: Усиление сферы, управляемой на основе ИТ', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-8: Жизненный цикл ПО', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-9: Управление изменениями мер по безопасности', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-10: Управление резервными копиями', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-11: Контроль доступа', true, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-12: Регистрация пользователей', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-14: Физическая безопасность', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-15: Управление непрерывностью', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-16: Сегментация и управление фильтрацией', true, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-17: Управление защитой от вредоносных программ', true, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-19: Внутренний технический аудит', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-20: Симуляция инцидентов', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-21: Анализ качества и соответствия информации', true, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-22: Проверка реагирования на инциденты', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-23: Логирование', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-24: Обработка инцидентов', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-25: Форензика', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-26: Повышение надёжности и доступность управления', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-27: Управление архивами', false, 5) RETURNING id;
INSERT INTO processes(id, name, is_important, role_id) VALUES(DEFAULT, 'OSP-28: Повышение надёжности и доступность управления', false, 5) RETURNING id;
